CREATE USER iceland identified by iceland;
GRANT CREATE SESSION TO iceland;

GRANT CONNECT, RESOURCE, dba TO iceland;
GRANT CREATE SESSION GRANT ANY PRIVILEGE TO iceland;
GRANT SELECT, INSERT, UPDATE, DELETE ON  TO  my_role;

GRANT CREATE TABLE TO iceland WITH ADMIN OPTION;